{% set version = "4.0.9" %}

# we only want a single python, but not make the package noarch
{% set min_python = "3.9" %}
# we just use a version here; doesn't seem to have much impact
{% set min_nodejs = "18" %}

package:
  name: emscripten
  version: {{ version }}

source:
  url: https://github.com/emscripten-core/emscripten/archive/{{ version }}.tar.gz
  sha256: 11a7d950453ee31da03ee3c3b261934ad3d7d2e470e41ea3222a13cecb9b98ef

build:
  number: 0
  string: h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
  ignore_run_exports_from:
    - python *
    - nodejs *

requirements:
  build:
    - {{ stdlib("c") }}
    - python {{ min_python }}
  host:
    - binaryen
    - nodejs {{ min_nodejs }}
    - lld
    - clang
    - clangxx
    - llvm-tools
    - llvm
  run:
    - python
    - {{ pin_compatible("binaryen", max_pin="x") }}
    - nodejs >={{ min_nodejs }}
    - lld
    - clang
    - clangxx
    - llvm-tools
    - llvm
    # for google closure compiler
    - zlib
  run_constrained:
    # otherwise linter complains (no py-constraints on non-noarch)
    - python >={{ min_python }}

test:
  requires:
    # test that we can co-install with another python than above
    - python ==3.10
  files:
    - testfile.c
  commands:
    - emcc --help
    - emcc ./testfile.c
    - node a.out.js

about:
  home: https://emscripten.org/
  license: MIT OR NCSA OR MPL-2.0
  license_file: LICENSE
  summary: Emscripten compiles C and C++ to WebAssembly using LLVM and Binaryen. Emscripten output can run on the Web, in Node.js, and in wasm runtimes.
  dev_url: https://github.com/emscripten-core/emscripten

extra:
  recipe-maintainers:
    - wolfv
    - h-vetinari
