{% set version = "3.1.58" %}

package:
  name: emscripten
  version: {{ version }}

source:
  url: https://github.com/emscripten-core/emscripten/archive/{{ version }}.tar.gz
  sha256: 45a6536b25df8f3bf62e0f415e389671108b02a49b33bd91134b2da7e87bab65

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}  # node modules need to compile native extensions
    - {{ stdlib("c") }}
  host:
    - python
    - binaryen
    - nodejs
    - lld
    - clang
    - clangxx
    - llvm-tools
  run:
    - python
    - {{ pin_compatible("binaryen", max_pin="x") }}
    - nodejs
    - lld
    - clang
    - clangxx
    - llvm-tools
    # for google closure compiler
    - zlib

test:
  files:
    - testfile.c
  commands:
    - emcc --help
    - emcc ./testfile.c
    - node a.out.js

about:
  home: https://emscripten.org/
  license: MIT OR NCAS
  license_file: LICENSE
  summary: Emscripten compiles C and C++ to WebAssembly using LLVM and Binaryen. Emscripten output can run on the Web, in Node.js, and in wasm runtimes.
  dev_url: https://github.com/emscripten-core/emscripten

extra:
  recipe-maintainers:
    - wolfv
    - h-vetinari
